using System;

namespace FixWorld.UI
{
    internal static class LoadingTips
    {
        private const double TipDurationMilliseconds = 8000.0;

        private static readonly string[] Tips =
        [
            // Community wisdom
            "Grow rice when supplies are short. Corn is for colonies confident they have a later.",
            "Potatoes handle poor soil. They also handle farmers who planted before checking it.",
            "Keep the butcher table out of the kitchen. Blood and dirt still count in rooms with stoves.",
            "A clean kitchen lowers food poisoning. The butcher table is why yours is not clean.",
            "Give cooking to a skilled pawn. Everyone else can haul ingredients without poisoning anyone.",
            "Nutrient paste prevents food poisoning and saves work. Pawns still complain because they have time now.",
            "A one-tile freezer airlock saves cold. The second door is cheaper than the sixth cooler.",
            "Coolers dump heat from the red side. Pointing it indoors warms the room you wanted cold.",
            "Double walls insulate better. This helps after you notice where you settled.",
            "Leave room for a spare cooler. The heat wave usually arrives before the rebuild.",
            "Limit bill ingredient radii. Your cook is trained in cooking, not cross-country.",
            "Set bills to drop products on the floor. Let haulers interrupt someone less valuable.",
            "Keep ingredients near workbenches. Walking is not a crafting speed bonus.",
            "Shelves hold several stacks and hide item beauty penalties. Pawns can finally see the floor.",
            "Put frequently used materials closest to the workshop. Steel on another continent is still steel.",
            "Rice grows quickly. Corn takes less work. You are allowed to plant both.",
            "Fine meals need vegetables and animal products. Your cook cannot replace either with enthusiasm.",
            "Packaged survival meals last on caravans. Raw berries last until someone gets sick.",
            "Grow medicine before the first epidemic. The traders are not monitoring your calendar.",
            "Devilstrand is excellent once food and medicine stop being theoretical.",
            "Dandelions feed penned animals efficiently. Haygrass works better after harvesting.",
            "Use auto-slaughter before the animals outnumber the colonists and eat their winter food.",
            "Zone animals away from crops unless the harvest plan includes being watched while they eat.",
            "Chickens produce food efficiently. A hundred chickens find your TPS limit just as efficiently.",
            "Train suitable animals to haul. Your researchers should not move leather one stack at a time.",
            "Stone walls do not burn. Their main weakness is requiring someone to plan ahead.",
            "Hidden conduits avoid Zzzt events and beauty penalties. Visible ones remain slightly cheaper.",
            "Firefoam poppers cost less than rebuilding. Wood enthusiasts may calculate differently.",
            "Store chemfuel away from bedrooms. Your shortest hauling route should not end the colony.",
            "Remove roofs before supports. The builder standing underneath gets the lesson first.",
            "Leave supports while mining large rooms. The roof falls on whoever happens to finish last.",
            "Wind turbines need clear lanes. Crops can grow there. Trees and roofs cannot.",
            "Keep batteries roofed. Rain turns stored power into an event notification.",
            "Use solar and wind together, then add batteries for the hours when both disappoint you.",
            "A geothermal generator heats enclosed rooms. Free winter heating becomes paid summer heating.",
            "Protect exposed coolers. Raiders also recognize a wall with an appliance-shaped hole.",
            "Combine dining and recreation rooms so both use the same impressiveness. Pawns call this two rooms.",
            "A beautiful barracks can beat several awful bedrooms. Pawns sometimes value marble over privacy.",
            "Put chairs at tables. A table alone is expensive floor decoration.",
            "Light work areas and corridors. Darkness slows movement, although it does not ruin shooting accuracy.",
            "Put beauty where pawns spend time. The marble hallway is not where they get their mood.",
            "Add recreation types before every pawn gets bored of horseshoes.",
            "A split sleep schedule can prevent breaks, at the cost of making every trip happen twice.",
            "Put night owls on night shifts. They are happier and everyone else sees them less.",
            "Use drug policies with safe intervals. Otherwise a binge chooses the dosage for you.",
            "Smokeleaf reduces pain and consciousness. A badly injured pawn may not have much consciousness to spare.",
            "A pyromaniac is manageable while everyone else is awake and far from the chemfuel.",
            "Keep corpses out of sight. Hauling them through the dining room is not the discreet route.",
            "Use manual priorities so growers harvest before they clean dirt outside.",
            "Passions multiply learning. Your skilled pawn may still learn slower than the excited beginner.",
            "Let your best builder finish quality furniture. The final worker gets the credit.",
            "Train Construction on forgiving projects before entrusting it with your masterwork bed.",
            "Keep hospitals clean, lit, and equipped. Installing a leg should not cost the patient a jaw.",
            "Self-tending carries a penalty. Your only doctor may still prefer it to bleeding politely.",
            "Set medical care per pawn. Glitterworld medicine is a costly treatment for bruised livestock.",
            "Train a second doctor. The first doctor has organs too.",
            "Suspend risky operations after raids. A wounded surgeon remains impressively willing.",
            "Raise Bed Rest priority when recovery matters. Otherwise patients resume stonecutting between treatments.",
            "Use a skilled, healthy warden. A beautiful prison keeps prisoners happy, not persuaded.",
            "Store weapons outside the prison. Prisoners will pick them up during breaks because somebody has to.",
            "Check held-open doors around prisoners and freezers. One toggle can heat the food and free the inmate.",
            "Use walls with barricades or sandbags so shooters can lean from real cover.",
            "Fight melee enemies in doorways. Three colonists can explain geometry to one target.",
            "Shield belts stop outgoing shots too. Your melee pawn was the intended customer.",
            "Smoke blocks turret targeting. Standing in smoke is cheaper than proving your armor works.",
            "EMP disables mechanoids, but repeated stuns make them adapt. Plan for when the sparks stop working.",
            "Helmets protect the brain. This is less exciting than a bionic leg and more relevant afterward.",
            "Heavy armor saves lives and slows movement. Arriving late is still preferable to never leaving.",
            "Tainted apparel still provides armor and insulation. The mood penalty is smaller than freezing to death.",
            "Match weapon range to the fight you built, not the fight described in a tier list.",
            "Keep shooters behind melee blockers. Putting both in one doorway gives the hospital more work.",
            "Focus dangerous weapons first. The raider with the club can wait behind the doomsday launcher.",
            "Give grenades room. The minimum safe distance is farther than optimism suggests.",
            "Mortars answer sieges and distant threats. Most shells answer a nearby patch of dirt.",
            "Traps need rebuilding after they fire. A long trap corridor is also a long construction bill.",
            "Turrets explode when destroyed. The colonist beside one will confirm this briefly.",
            "A killbox works until breachers, sappers, drop pods, or insects choose another entrance.",
            "Build fallback positions inside the base. One entrance is a defense plan. The rest still exist.",
            "Breachers and drop pods inspect the parts of your layout omitted from screenshots.",
            "Close doors during manhunter packs. The pawn fetching one slag chunk can wait.",
            "Zone children and small animals away from predators. A hungry cougar prefers easy work too.",
            "Hunt herd animals only when prepared for group revenge. The warning names the group.",
            "Mountain bases need internal melee chokepoints. The insects already have an entrance.",
            "Deep-freezing mountain rooms suppresses infestations. It also stops them being useful bedrooms.",
            "Colony wealth increases raid strength. That legendary dining chair is part of the defense budget.",
            "Floors, buildings, animals, and spare gear count as wealth. The raid sees what you forgot you owned.",
            "Sell or destroy loot you will never use. Raiders appreciate collections even when colonists do not.",
            "Do not stack optional threat quests unless the rewards include a second colony.",
            "Goodwill can buy military aid. Allies are cheaper than replacing a favorite pawn.",
            "Cassandra applies pressure on schedule. Randy sometimes forgets. Randomness is not a difficulty setting.",
            "Phoebe allows long recovery and equally long complacency. The eventual raid still reads the wealth total.",
            "Lower or customize difficulty when the run stops being fun. Pride has no mood bonus.",
            "Reload when that preserves the story you want. Commitment mode has no achievement for resentment.",
            "Launching the ship ends the colony. Starting over when the reactor is nearly ready does not.",
            "Bring bedrolls on caravans. The ground is free because nobody recommends it.",
            "Pack more food than the route predicts. Detours rarely bring their own lunch.",
            "Caravans slow near their mass limit. The sixth marble statue can stay home.",
            "Plants skill improves foraging when the biome allows it. Ice sheets are not one of those biomes.",
            "Check seasonal movement. A two-day summer route can become winter housing.",
            "Place caravan packing spots near storage and exits. Crossing the base twelve times is optional.",
            "Send medicine and someone able to use it. The best doctor cannot tend from the home tile.",
            "Keep trade goods inside powered beacon range. Orbital traders cannot see your other warehouse.",
            "Transport-pod gifts improve relations. Diplomacy becomes simpler once it has a market value.",
            "Back up saves before changing mods. Confidence is not a rollback strategy.",
            "Avoid removing content mods mid-save. The save will keep asking where its things went.",
            "Read the first relevant red error, not the hundred consequences below it.",
            "Check dependencies and load order before blaming the last mod shown on screen.",
            "Mod count predicts little by itself. One ambitious framework can outwork fifty hairstyle packs.",
            "Pawns, animals, jobs, and paths consume ticks. Texture packs usually spend memory instead.",
            "Shorter routes and fewer doors help performance. Your decorative maze is being simulated faithfully.",
            "Combat Extended changes the rules of combat. A compatibility patch does not restore vanilla balance.",
            "Vanilla Expanded is a collection, not a promise to install the collection.",
            "Play enough vanilla to learn which problem a mod solves. Otherwise every feature is quality of life.",
            "Five hundred quality-of-life mods still take time to load. Startup was apparently excluded.",
            "Killboxes are cheating only in the competitive RimWorld league that nobody can locate.",
            "Open-field defenses create better stories, especially for players who survive them.",
            "Cannibal colonies are rare enough to appear in every discussion about ordinary colonies.",
            "Organ harvesting is optional. So is funding the hospital through conventional trade.",
            "There is no wrong way to play, but some players have prepared documentation to the contrary.",
            "Forbid emergency meals until the caravan leaves. Gourmands can locate them without assistance.",
            "Keep pets out of kitchens and freezers. Animal filth has no Cooking requirement.",
            "Separate crop fields with gaps. Blight spreads faster than growers accept new orders.",
            "Harvest ripe crops before a cold snap. Frozen mature corn feeds nobody.",
            "Prepare an indoor zone before toxic fallout. Naming it afterward still feels productive.",
            "Limit the home area. Pawns clean every outdoor tile you mark before noticing blood indoors.",
            "Exclude apparel below 51% hit points. Pawns keep tattered clothes on just to complain about them.",
            "Inspired crafters use the next eligible item. Suspend the stool bill if you wanted a weapon.",
            "Check every bleeding pawn after a raid. An undrafted doctor may decide dinner comes first.",
            "Draft or zone noncombatants during raids. The cleaner does not need to inspect the killbox.",
            "Keep boomalopes away from chemfuel and turrets. They bring their own explosion.",
            "Put small tables near remote work sites. Pawns decide a table is too far away long before you do.",
            "Builders can wall themselves into rooms. Leave the doorway for last if this still surprises you.",
            "Solar flares stop powered coolers. Insulation and closed doors buy time. Complaining does not.",
            "Check work priorities on every recruit. The game does not know what you hired them for.",
            "Keep antigrain warheads away from tantrum targets. Tantrums do not read market value.",
            "Keep beer away from animals or zone them out. A blackout muffalo still counts as livestock.",

            // Dry emergency guidance
            "If a pawn is bleeding, stop the bleeding.",
            "If your colonists are starving, food remains a popular treatment.",
            "A pawn on fire is less productive than the same pawn not on fire.",
            "Pawns without heads complete fewer assigned jobs.",
            "Fire becomes less dangerous after it is extinguished.",
            "Sleeping pawns are less effective at firefighting.",
            "If the doctor is downed, medical staffing has decreased.",
            "A prison without prisoners cannot have a prison break.",
            "A prisoner holding a weapon is more armed than intended.",
            "Rooms are easier to enter when they have doors.",
            "A held-open door remains open.",
            "If the freezer is above freezing, it is currently a room.",
            "A cooler facing backwards heats the room successfully.",
            "Unpowered sun lamps produce less artificial sunlight.",
            "A solar panel produces less power under a roof.",
            "A blocked wind turbine is now scenery.",
            "Batteries cannot store power they never received.",
            "A roof collapse is easier to prevent before the roof collapses.",
            "Crops grow poorly after being eaten.",
            "A boomalope that has exploded requires less pen food.",
            "Weapons usually work better after being equipped.",
            "Melee weapons work best within melee range.",
            "Dead raiders are usually less dangerous than living raiders.",
            "When every colonist is incapable of violence, raids remain capable of violence.",
            "Research progresses faster while somebody researches.",
            "Pawns do not haul forbidden items. They are respecting your decision.",
            "An idle pawn has completed every job they are allowed to notice.",
            "Sleeping colonists are rarely awake.",
            "A missed mortar shell still landed somewhere.",
            "Caravans arrive after they finish traveling.",
            "A table too far away is functionally decorative.",
            "A missing colonist may still be where you last drafted them.",
            "If everyone is dead, colony management becomes considerably simpler.",
            "The loading screen normally disappears when loading is complete.",

            // Royalty
            "Do not accept titles faster than you can meet their demands. The Empire hands out honor, not bedrooms.",
            "Leave royal rooms space to expand. Higher titles discover standards at predictable moments.",
            "Several nobles can share a throne room. One expensive room can satisfy several expensive people.",
            "Royal couples can share a bedroom and throne room. Marriage finally reduces the building queue.",
            "Check a pawn's meditation focus before designing the shrine they cannot use.",
            "Set a psyfocus target so meditation enters the schedule before the emergency.",
            "Watch neural heat during combat. A powerful psycaster can still become a spectator.",
            "Tribal natural psycasters can grow anima grass by meditating near an undisturbed anima tree.",
            "Keep buildings away from the anima tree. Nearby construction slows anima grass growth.",
            "Psycasts can end fights before damage starts. Stun and Skip stay useful all game.",
            "Bond persona weapons carefully. Their traits stay with the wielder for life.",
            "Smoke and EMP launchers solve mech turrets more cheaply than prestige armor repairs.",
            "Use permits before the colony is lost. Military aid cannot revive the people it was meant to help.",
            "Tribute collectors trade honor for gold and prisoners. The Empire does not ask how you obtained either.",
            "Keep Imperial goodwill high enough for permits and trade. The fine flooring already cost enough.",
            "Clear paths and reserve the throne before bestowing. Making the bestower wait impresses nobody.",

            // Ideology
            "Convert prisoners before recruitment when unity matters. The prison tab has a button for the awkward part.",
            "A high-Social moral guide converts better. Belief also has a talking stat.",
            "Use conversion rituals when daily conversion takes too long. Attendance and room quality still matter.",
            "Ritual quality depends on attendance, roles, room, and listed requirements. Read the list before blaming faith.",
            "Fill required ritual roles first. Empty roles lower quality even in a magnificent room.",
            "Specialists gain strong bonuses and lose work types. Check what your best pawn will stop doing.",
            "Fluid ideoligions need development points to reform. Flexibility has a progress bar.",
            "Choose precepts for the colony you will run, not the screenshots you intend to post.",
            "Food precepts decide whether nutrient paste is efficient or an organized insult.",
            "Multiple ideoligions add cultural variety and several new reasons to start social fights.",
            "Keep corpses, disliked clothes, and forbidden foods away from pawns whose precepts reject them. They notice.",
            "Slave collars and body straps slow suppression loss. Regular clothes make rebellion more comfortable.",
            "Terror raises suppression, but not loyalty. The distinction becomes relevant during rebellions.",
            "Schedule Gauranlen pruning deliberately. Dryads are powered by someone's entire afternoon.",
            "A biosculpter pod biotunes to its user. Sharing begins after the long reset nobody planned for.",
            "Relics provide mood and pilgrimage opportunities once obtained. Before that, they provide quests.",
            "Check work restrictions before assigning roles. Your best crafter can become ceremonial very quickly.",
            "A beautiful ritual room cannot replace missing participants. Empty chairs do not count as believers.",

            // Biotech
            "Give children free time for learning. Eight hours of hauling teaches exactly one lesson.",
            "Higher learning raises growth tiers and improves growth choices. A bad schedule takes years to report itself.",
            "Cribs can share a parent's bedroom without creating a barracks. Babies do not count as roommates.",
            "Growth vats skip helpless infancy well. Using them through childhood also skips much of childhood.",
            "Assign childcare before scheduling births. Biology does not create a work priority.",
            "Endogenes can be inherited. Xenogenes generally cannot. Custom design stops at the next generation.",
            "Balance xenogerms with metabolism. Free advantages become less free when the pawn eats continuously.",
            "Store genepacks in powered gene banks. Ordinary shelves let them deteriorate.",
            "Wait for genes to regrow before extracting again. The second extraction can kill the donor.",
            "Archite genes need archite capsules. Gene extraction does not provide them.",
            "Utility mechs save labor and create charging and waste work. Plan both before building a swarm.",
            "Bandwidth limits controlled mechs. Mechanitor gear can raise it, usually at the cost of better armor.",
            "Set mech work modes and zones. An unrestricted lifter can optimize the wrong stockpile indefinitely.",
            "Dormant self-charge saves infrastructure when a mech is not needed quickly.",
            "Rechargers make toxic wastepacks. The cleaner mech does not clean those.",
            "Freeze wastepacks until disposal is ready. Keeping them beside food only solves storage.",
            "Dumping waste near factions can provoke retaliation. They know which colony launched it.",
            "Hemogen packs can treat blood loss too. Keep some where the doctor can reach them.",
            "Keep firefoam near sanguophages. One fire can undo most of their advantages.",
            "Schedule deathrest before major fights. Starting when the raid arrives is still a schedule.",

            // Anomaly
            "Upgrade containment doors before walls. A good door adds more containment than expensive wall material.",
            "Healthy walls raise containment. Repair damage before the entity uses it.",
            "Separate dangerous entities when one weak room would lower everyone's containment.",
            "Higher containment improves study safety and progress. Research benefits from fewer interruptions.",
            "Assign reliable wardens to suppress entities. Stonecutting can wait until containment is stable.",
            "Inspect each entity's containment requirements. One room fits all until something proves otherwise.",
            "Keep a second barrier outside containment. Redundancy is cheaper before the breach.",
            "Restore damaged doors and walls immediately. Entities do not wait for the construction queue.",
            "Study captured entities before disposing of them. Dead specimens are safer and less informative.",
            "Bioferrite harvest needs living contained entities. The machine stops when containment does.",
            "Activating the monolith increases Anomaly activity. The button does what the warning says.",
            "Disruptor flares reveal revenants. Shooting the empty room remains the less technical option.",
            "Investigate metalhorror clues before routine surgery spreads the staffing problem.",
            "Separate suspects when evidence appears. An infected doctor is still allowed to perform surgery.",
            "Place lights before unnatural darkness. Lamps in storage do not help the firing line.",
            "Prepare fighters before provoking mysterious objects. Curiosity does not count as armor.",
            "Containment cells need nearby response routes. The researchers are not the response team.",
            "The safest entity is the one currently behind the door you remembered to repair.",

            // Odyssey
            "Only structures on connected substructure travel. The chair one tile off stays there.",
            "A flightworthy gravship needs a grav engine, pilot console, fuel tank, thruster, and connected substructure.",
            "Gravship travel burns chemfuel per tile and has a minimum launch cost. A short hop is not almost free.",
            "More thrusters increase range only when the tanks have fuel. Count both before launch.",
            "Fuel optimizers reduce per-tile consumption, up to the supported limit of two.",
            "Choose and rotate the landing footprint carefully. The destination will not reorganize itself.",
            "Clear the thruster exclusion areas before the next launch. Landing somewhere was the easy half.",
            "Carry components and repair materials. Mobile colonies break in more interesting locations.",
            "Better launch ritual quality reduces landing mishaps. Competent pilots beat hoping the floor survives.",
            "A grav engine must cool after landing. It will not launch early because the map is on fire.",
            "Orbit requires vacuum protection such as sealed rooms with oxygen or vacsuits.",
            "A signal jammer is needed for certain orbital locations. Finding one without it only adds a map marker.",
            "Landing on a faction base starts an attack, not trade. Pack guns instead of silver.",
            "Without a grav anchor, leaving abandons the map. You cannot fly back for forgotten items.",
            "Pawns left on an abandoned map are lost. Check the colonist bar before launch.",
            "Anything off connected substructure stays behind. This includes the part that looked close enough.",
            "Landing on an ordinary tile creates a new colony. It is not treated as a brief parking stop.",
            "Check fuel, passengers, blocked thrusters, and repairs before launch. The button checks less than you hope."
        ];

        private static readonly int StartIndex =
            (int)((uint)Environment.TickCount % (uint)Tips.Length);

        internal static string Get(double elapsedMilliseconds)
        {
            long rotation = (long)(Math.Max(0.0, elapsedMilliseconds) /
                                   TipDurationMilliseconds);
            return Tips[(int)((StartIndex + rotation) % Tips.Length)];
        }
    }
}
