using System;

namespace FixWorld.UI
{
    internal static class LoadingTips
    {
        private const double TipDurationMilliseconds = 8000.0;

        private static readonly string[] Tips =
        [
            "If your colonists are starving, you need more food.",
            "If your base is burning down, you should have less fire.",
            "Pawns sleep better in beds than on the floor.",
            "Coolers work better when they have power.",
            "If your colonists keep dying, try keeping them alive.",
            "If your freezer is too warm, make it colder.",
            "If you run out of food, produce more food.",
            "If raiders destroy your colony, you need better defenses.",
            "If your defenses do not work, build better defenses.",
            "If your pawns are unhappy, improve their mood.",
            "If a pawn is bleeding, stop the bleeding.",
            "If your colonists have no medicine, get some medicine.",
            "If you are short on steel, you need more steel.",
            "If you are short on components, you should have more components.",
            "If your battery is empty, charge it.",
            "Solar panels produce less power at night. Plan accordingly.",
            "If your wind turbine produces no power, check whether it produces power.",
            "If your plants are not growing, make sure they grow.",
            "Plants grow faster when they are not dead.",
            "If your crops freeze, it was probably too cold.",
            "If your crops burn, it was probably too warm.",
            "No table? Build one.",
            "Can't get Ate without a table if nobody eats. Finally, peace.",
            "If your bedroom is ugly, make it prettier.",
            "If a room is dark, light helps.",
            "If your colonists sleep outside, give them an inside.",
            "Rooms work better with walls.",
            "Doors are useful when you want to enter rooms.",
            "If a door is open, it is not closed.",
            "If a room is too small, you can make it bigger.",
            "If your colonists are cold, make them warmer.",
            "If your colonists are overheating, make them cooler.",
            "If your colonists are tired, they should sleep.",
            "If your colonists are hungry, they should eat.",
            "If your colonists are bored, they need recreation.",
            "If your colonists are sick, treat them.",
            "Doctors are more useful when Doctoring is enabled.",
            "A doctor without a patient treats fewer patients.",
            "If an operation fails, a successful operation would have been better.",
            "Pawns without legs have difficulty walking.",
            "Pawns without eyes have difficulty seeing.",
            "Pawns without heads tend to have bigger problems.",
            "If your pawn loses in melee, use a stronger pawn.",
            "Melee works better when the enemy is nearby.",
            "Guns work better when you shoot at something.",
            "Missed shots rarely hit the target.",
            "If your pawns have no weapons, give them weapons.",
            "If a raid is too difficult, make it easier.",
            "Dead raiders are usually less dangerous than living raiders.",
            "Mechanoids cause fewer problems after they are destroyed.",
            "Insects are easier to fight when there are fewer insects.",
            "If an infestation destroys your base, prevent that.",
            "If boomalopes are burning, keep your distance.",
            "Boomalope already exploded? Bit late to stop it now.",
            "Wood is a poor choice if you dislike fires.",
            "Stone is worse at burning than wood.",
            "If your wooden base keeps burning down, use less wood.",
            "If your colonist catches fire, extinguish the fire.",
            "Fire is less dangerous after it has been extinguished.",
            "Rain helps against fire when the fire is in the rain.",
            "If your prisoners keep escaping, imprison them more effectively.",
            "Prisoners have more trouble escaping through walls than through open doors.",
            "A prison without prisoners cannot have a prison break.",
            "If your animals are starving, feed them.",
            "Animals need less food when you have fewer animals.",
            "If you have too many animals, you could have fewer animals.",
            "If your chickens destroy your TPS, fewer chickens may be a solution.",
            "An animal outside its allowed area is outside its allowed area.",
            "If a pawn cannot find a path, there is probably no path.",
            "Paths are easier to use when they lead to the destination.",
            "If your pawns walk too slowly, they should walk faster.",
            "Doors slow pawns down less when there are no doors in the way.",
            "If your colonists constantly open doors, you probably have many doors.",
            "A route tends to get shorter when you make it shorter.",
            "If your caravan is too slow, travel faster.",
            "Caravans arrive sooner when the journey takes less time.",
            "If your caravan runs out of food, bring more food.",
            "Still waiting for the caravan? Then it isn't back yet.",
            "If you have no trading partner, you cannot trade with them.",
            "Can't afford it? More silver may solve that.",
            "Expensive items cost more than cheap items.",
            "If your colony is poor, become richer.",
            "If you have no resources, gather resources.",
            "Mining works better in places with rock.",
            "If you cannot find ore, look where the ore is.",
            "Research moves faster when somebody actually researches.",
            "Less research happens when nobody works at the research bench.",
            "If you are missing a technology, research it.",
            "If mods slow down startup, install fewer mods.",
            "RimWorld loads faster when it has less to load.",
            "Twenty-minute startup? Give it twenty minutes.",
            "If the game appears frozen while loading, it may still be loading.",
            "The loading screen usually disappears once loading finishes. Usually.",
            "If your FPS is low, you need more FPS.",
            "If your TPS is low, you need more TPS.",
            "If RimWorld runs slowly, make it run faster.",
            "Mods can hurt performance. Performance-hurting mods are frequent offenders.",
            "If a mod is incompatible, a compatible version would be better.",
            "If your save is broken, use a save that is not broken.",
            "Nothing works? Statistically, you probably did something.",

            "If your freezer stops freezing, it may no longer be a freezer.",
            "Colonists work faster when they spend less time not working.",
            "A pawn moves faster when its movement speed is higher.",
            "Sleeping colonists are rarely awake.",
            "A hospital without beds is mostly just a room.",
            "Food poisoning is easier to avoid when nobody gets food poisoning.",
            "Clean kitchens are cleaner than dirty kitchens.",
            "Bad cook? More Cooking skill has been known to help.",
            "More storage space allows you to store more things.",
            "Items on the floor remain items, despite appearances.",
            "Your stockpile works better when items are allowed in it.",
            "If a stockpile is full, additional storage may provide more storage.",
            "Colonists are more productive when they are not having mental breaks.",
            "Preventing a mental break is easier before the mental break happens.",
            "If a pawn is about to break, making them happier may make them less likely to break.",
            "Recreation deprivation can be reduced with recreation.",
            "Drafting an undrafted pawn usually fixes the undrafted part.",
            "Enemies outside weapon range are harder to shoot with that weapon.",
            "Long-range weapons have longer range. It's in the name.",
            "Armor protects pawns better when they are wearing it.",
            "Helmets work best on heads. Ideally attached ones.",
            "A spare arm is useful after losing the first one.",
            "Medicine cannot be consumed by a patient if you have no medicine.",
            "Colonists heal faster when their injuries heal faster.",
            "Rescuing a downed pawn is easier before they die.",
            "Dead colonists have notoriously poor work speed.",
            "Corpses require less food than living colonists.",
            "If your colony has too many corpses, having fewer corpses may improve things.",
            "Raids are easier when the raiders are weaker.",
            "More turrets give you more turrets.",
            "Turrets are less useful when they cannot shoot the enemy.",
            "Cover works better when the pawn is behind it.",
            "Standing in front of cover provides less cover than standing behind it.",
            "Friendly fire drops sharply when you stop shooting friendlies.",
            "A missed mortar shell still landed. Probably somewhere else.",
            "Mortars become more accurate as accuracy improves. Weird.",
            "Explosions are safer when you are farther away from them.",
            "Chemfuel is less dangerous while it is not on fire.",
            "Power conduits are most useful when they connect powered things.",
            "Power shortages are less common when you produce enough power.",
            "Batteries cannot store power they never received.",
            "Batteries keep exploding? Aim for fewer battery explosions.",
            "Geothermal generators work best near geothermal vents.",
            "Sun lamps require power to produce artificial sunlight.",
            "Hydroponics basins grow fewer crops when they are not powered.",
            "If your crops die before harvest, harvesting them earlier might have helped.",
            "Animals reproduce more slowly when there is only one of them.",
            "Pregnant animals give birth more often than the others.",
            "Tamed animals are generally more tame than wild animals.",
            "Wild animals become less wild after they are tamed.",
            "If predators eat your colonists, reducing the number of predators may help.",
            "Manhunter animals are less dangerous after they stop hunting humans.",
            "Visitors who leave are generally no longer visiting.",
            "Traders sell things more effectively when you buy them.",
            "Quest rewards are commonly awarded after the quest.",
            "If a quest is too dangerous, accepting it may expose you to danger.",
            "Declining a quest remains the most reliable way not to fail it.",
            "Save files are easier to load when they exist.",
            "Autosaves work best once saved.",
            "If the game crashes before saving, a previous save may be older.",
            "Performance improves when the game spends less time doing work.",
            "Lower tick times are a reliable source of lower tick times.",
            "Pathfinding is faster when pawns need fewer paths.",
            "Doors are less expensive to path through when pawns do not path through them.",
            "If 200 animals slow down your colony, try 199. Small steps.",

            // Base game, actually useful
            "Actual tip: A one-tile airlock helps your freezer lose less cold when pawns enter.",
            "Actual tip: Corn gives more food per unit of work; rice gives food sooner.",
            "Actual tip: Remove roofs before their supporting walls. Falling roofs hurt.",
            "Actual tip: Fine meals need both vegetarian and meat ingredients, but they improve mood.",
            "Actual tip: Each shelf cell holds multiple stacks and hides their beauty penalty.",

            // Royalty
            "Nobles are easier to please when they have fewer reasons to complain.",
            "A throne gets more use once somebody is entitled to sit on it.",
            "Better throne rooms are generally better throne rooms.",
            "Noble demands a bedroom? A bedroom may satisfy the bedroom demand.",
            "Royal apparel works better when the noble is wearing it.",
            "Titles become more useful after somebody receives them.",
            "Honor is easier to spend when you have honor.",
            "Need more honor? Acquiring honor increases your available honor.",
            "Psyfocus is easier to use when you have psyfocus.",
            "Psycasts cannot be cast by pawns that cannot cast that psycast.",
            "Meditation builds psyfocus faster when the pawn actually meditates.",
            "Meditation spots are more useful when somebody meditates at them.",
            "Neuroformers are easier to use before somebody else uses them.",
            "Permits remain unavailable for the entire time they're unavailable.",
            "Call military aid before everybody dies. Timing matters.",
            "The Empire is friendlier when your relations with the Empire are better.",
            "If you anger the Empire, making them less angry may help.",
            "Royal quests are easier when their requirements are easy.",
            "Actual tip: A pawn's meditation focus determines which objects they can use for psyfocus.",
            "Actual tip: Tribute collectors accept gold and prisoners in exchange for honor.",

            // Ideology
            "Colonists are happier with their ideology when they like their ideology.",
            "Beliefs only affect pawns who believe them. Shocking.",
            "Converting a pawn is easier after their certainty becomes lower.",
            "Zero certainty is closer to conversion than 100%. The numbers do most of the work.",
            "Conversion rituals work better when the conversion ritual works.",
            "Ritual quality improves when fewer things reduce ritual quality.",
            "Non-participants make poor ritual participants.",
            "Your ritual room works better when it satisfies the ritual room requirements.",
            "Relics are easier to display after you obtain them.",
            "Lost relics are notoriously difficult to put in reliquaries.",
            "Specialist roles are most effective after somebody is assigned to them.",
            "Leaders lead more effectively after becoming leaders.",
            "Moral guides can only guide pawns that exist.",
            "Precepts cause fewer mood penalties when colonists agree with them.",
            "If your ideology forbids something, doing that thing may upset believers.",
            "Colonists dislike forbidden food less when they do not eat it.",
            "Cannibals are generally more accepting of cannibalism.",
            "Nudists object less to nudity than people who object to nudity.",
            "Slaves work more effectively when they are not rebelling.",
            "Slave rebellions are rare when none of the slaves rebel.",
            "Gauranlen trees produce fewer dryads when nobody connects to them.",
            "Actual tip: Fluid ideoligions need development points before they can reform.",
            "Actual tip: Ritual quality depends on attendance, the room, and fulfilled roles.",

            // Biotech
            "Children are younger than adults until they become adults.",
            "Babies do fewer jobs than adults. This is apparently acceptable.",
            "Children learn more while learning. Scheduling helps.",
            "Growth tiers are easier to reach when children gain enough growth.",
            "A child with no learning opportunities has fewer learning opportunities.",
            "Pregnancy usually ends after the baby is born.",
            "Genes start affecting pawns once the pawns actually have them.",
            "Xenotypes are different when they contain different genes.",
            "Good genes are more useful when you consider them good.",
            "Bad genes tend to be the ones causing problems.",
            "Gene packs are easier to implant after you obtain them.",
            "A gene bank stores more genes when you put more genes in it.",
            "Mechanoids require bandwidth unless they do not require bandwidth.",
            "If you run out of bandwidth, obtain more bandwidth or use less bandwidth.",
            "Bandwidth packs provide more bandwidth while equipped.",
            "Mechanoids work better while they are under control.",
            "Uncontrolled mechanoids suffer from reduced control.",
            "A mechanitor controls more mechs when their control capacity is higher.",
            "Mech rechargers recharge mechs faster when the mech uses the charger.",
            "Mechs with no power work worse than mechs with power.",
            "Gestation completes faster when more of the gestation has already completed.",
            "Pollution is less of a local problem when it is somewhere else.",
            "Wastepacks are easier to ignore after launching them at somebody else. Diplomacy may vary.",
            "Wastepack infestations are less likely when the wastepacks are not there.",
            "Polluted terrain contains more pollution than unpolluted terrain.",
            "Fire is less effective at removing pollution than removing pollution is.",
            "Sanguophages need less hemogen immediately after receiving hemogen.",
            "A sanguophage cannot drink hemogen packs you do not have.",
            "Deathrest works best while the sanguophage is deathresting.",
            "Fire is especially inconvenient for pawns who are afraid of fire.",
            "Actual tip: Children need free time for learning; a full work schedule is not an education.",
            "Actual tip: Toxic wastepacks do not deteriorate while safely frozen.",

            // Anomaly
            "Unknown entities become easier to identify once they're known.",
            "Studying an entity provides more research when the entity can be studied.",
            "Containment works best when the contained thing stays contained.",
            "A containment cell with no contained entity contains fewer entities.",
            "Stronger containment strength provides stronger containment.",
            "Entities are less dangerous when they cannot reach your colonists.",
            "If an entity escapes, putting it back is the traditional way to restore containment.",
            "Anomaly research progresses faster when you generate anomaly research.",
            "More advanced anomaly research requires more anomaly research.",
            "Unnatural darkness contains less natural light than normal darkness.",
            "Light is more useful against darkness when it produces light.",
            "Things hiding in the darkness are harder to see while it is dark.",
            "Metalhorrors cause the fewest problems before they exist.",
            "A colonist without a metalhorror is less likely to contain that metalhorror.",
            "Suspected colonists are easier to investigate after you suspect them.",
            "Revenants are easier to shoot while visible.",
            "Invisible threats are harder to see than visible threats.",
            "Fleshbeasts are easier to kill after taking enough damage.",
            "Dead entities are famously undemanding containment subjects.",
            "An entity cannot escape your containment if you never contained it.",
            "Disturbing mysterious objects may produce mysterious consequences.",
            "Leaving mysterious objects alone reduces the number of times you disturb them.",
            "If the void is causing problems, interacting with the void may cause additional problems.",
            "Anomalies are generally less normal than normal things.",
            "Actual tip: Strong walls and doors matter to containment, not just the holding platform.",
            "Actual tip: Don't disturb mysterious objects if you dislike mysterious consequences.",

            // Odyssey
            "Gravships travel farther when they do not run out of fuel.",
            "A gravship without enough fuel has less fuel than it needs.",
            "Fueling a gravship has been shown to increase its fuel.",
            "A gravship cannot take off before it is capable of taking off.",
            "Required gravship parts are, regrettably, required.",
            "Missing gravship parts work much better once found and installed.",
            "A gravship with all required components has fewer missing required components.",
            "Your destination becomes closer as you approach your destination.",
            "Landing safely remains safer than crashing.",
            "Dangerous landing zones are generally more dangerous than safe landing zones.",
            "A hostile destination may contain hostility.",
            "Exploration reveals more of an area after you explore it.",
            "Unexplored locations are less explored than explored locations.",
            "Travel takes less time when the journey is shorter.",
            "A gravship parked at your colony is easier to access than one somewhere else.",
            "Moving your colony somewhere else results in your colony being somewhere else.",
            "If your gravship is damaged, repairing it may make it less damaged.",
            "Colonists aboard the gravship travel with it. The others do not.",
            "Colonists left behind rarely end up aboard the departing gravship.",
            "Anything you leave behind will remain convincingly behind.",
            "Resources found while exploring are easier to bring home if somebody brings them home.",
            "Reaching your destination is easier when you know where the destination is.",
            "Actual tip: Pack repair materials. Mobile colonies still break.",
            "Actual tip: Check the passenger list before takeoff; left-behind pawns stay left behind."
        ];

        private static readonly int StartIndex =
            (int)((uint)Environment.TickCount % (uint)Tips.Length);

        internal static string Get(double elapsedMilliseconds)
        {
            long rotation = (long)(Math.Max(0.0, elapsedMilliseconds) /
                                   TipDurationMilliseconds);
            return Tips[(int)((StartIndex + rotation) % Tips.Length)];
        }
    }
}
