<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472"
            Version="1.0.3" PrivateAssets="all" />
        <Compile Include="../../Source/Settings/SettingsPanel.cs" Link="SettingsPanel.cs" />
        <Compile Include="../../Source/Settings/ModSettingsPack.cs" Link="ModSettingsPack.cs" />
        <Compile Include="../../Source/Settings/SettingHandle.cs" Link="SettingHandle.cs" />
        <Compile Include="../../Source/Settings/SettingHandleConvertible.cs"
            Link="SettingHandleConvertible.cs" />
        <Compile Include="../../Source/Settings/Validators.cs" Link="Validators.cs" />
    </ItemGroup>
</Project>
