<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../../Bootstrap/FixWorld.Bootstrap.csproj" />
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472"
            Version="1.0.3"
            PrivateAssets="all" />
        <PackageReference Include="Lib.Harmony" Version="2.4.1" />
        <Reference Include="System.Web.Extensions" />
        <Compile Include="../../Source/Profiling/*.cs" Link="Profiling/%(Filename)%(Extension)" />
        <Compile Include="../../Source/Telemetry/*.cs" Link="Telemetry/%(Filename)%(Extension)" />
        <Compile Include="../../Source/Utils/DistributedTickScheduler.cs"
            Link="DistributedTickScheduler.cs" />
        <Compile Include="../../Source/UI/LoadingProgress.cs" Link="LoadingProgress.cs" />
        <Compile Include="../../Source/UI/LoadingTips.cs" Link="LoadingTips.cs" />
        <Compile Include="../../Source/Patches/DeferredWorkPump.cs" Link="DeferredWorkPump.cs" />
        <Compile Include="../../Source/Patches/ModLoadingHooks.cs" Link="ModLoadingHooks.cs" />
    </ItemGroup>
</Project>
